### ISSUE TITLE
Revise account holder library API for deterministic key derivation

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-base#160]
**Task description**

In order to support identity and account recovery the mobile wallet is transitioning to deterministic key derivation. The library for deterministic key derivation has been created already in #157 but this now needs to be integrated into the current mobile wallet API.

In particular the mobile wallet uses two functions
- create_id_request_and_private_data
- create_credential

These are the ones that currently generate keys and randomness that will need to be generated deterministically.

**Sub-tasks**
- [x] Make it possible to use given randomness in the account_holder.rs functions. Currently this samples randomness from the operating system.
- [x] Revise the API of the above mentioned mobile wallet functions to take the input (seed and identity index for the `create_id_request_and_private_data` and seed, identity, and credential index for `create_credential`.
- [ ] In principle we can make it so that the API is backwards compatible, and the library falls back onto sampling all the randomness and keys from the OS if the relevant context is not provided.
