### ISSUE TITLE
Update command line tools for the identity issuance process

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-base#171]
**Task description**

We maintain a number of tools for testing and ad-hoc identity issuance. These are

- [ ] `client`
- [ ] `user_cli`
- [ ] `identity_provider_cli`

The latter two are used in production for company identity issuance and so must be updated and new versions need to be released whenever the initial account removal will be rolled out.

Open questions
- [ ] Does the user_cli/identity_provider_cli need to support id recovery. Seeing that company identity issuance is a manual process this does not seem necessary.

The minimal change to the client is support for 
- [ ] generating V1 requests (also from a seed phrase and indices)
- [ ] validating V1 requests
- [ ] generating credentials from seed phrases (and indices)
