### ISSUE TITLE
Ask for password confirmation and minor cleanup

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-base#19]
**Task description**

- [x] The keygen tool asks for a password to encrypt the generated keys under.
We should make it less error prone by asking them to enter it again as a confirmation.

- [x] The same should be done in the "utils" tool which can also encrypt data.

- [x] In the anonymity revocation tool remove the prints of decrypted data. These are just leftovers from before and all the data is written to files already.

**Comment by abizjak** [comment]
Resolved in PR #23
