### ISSUE TITLE
Parameters for new finalization committee selection

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-base#303]
**Task description**

In P6 and in particular with the new consensus protocol coming along we want to change the way of how the finalization committee is determined. 

In particular the following parameters for controlling the finalization committee are being introduced:

- Minimum number of finalizers
- Base CCD threshold for becoming a finalizer.
- Maximum number of finalizers

This issue is just about adding the parameters and another issue will cover the handling of these new parameters, i.e. picking the finalization committee for a payday. 

- [x]  add a new FinalizationCommitteeParameters structure for holding the parameters deciding which bakers gets to join the finalization committee (for the new consensus protocol only)
- [x]  Authorization for invoking a chain update in order to change the parameters.
- [x]  expose in grpc2

**PRs**

- [x]  GRPC
- [x] Base
- [x] Node 
- [x] Client
- [x] WP
- [x] TR
