### ISSUE TITLE
Revise packaging of rust-src libraries.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-base#335]
**Task description**

Revise packaging of rust-src libraries so that they can be published on crates.io.

- [x] Remove the sha2 crate and replace the usage in Haskell with cryptonite version.
  - This is not workable due to the benchmark results below.
- [x] Move all crates except key derivation ones and crypto-common-derive as modules inside concordium-base.
- [x] Create concordium-base-derive and move crypto-common-derive there.
- [x] Propagate changes to the node.
- [x] Propagate changes to the client, wallet-proxy, tokenomics reporter (mainly shared libraries and any build jobs that explicitly copy those).
- [x] Propagate changes to the Rust SDK.
- [x] Publish concordium-base and concordium-base-derive.
- [x] Publish Rust SDK.
