### ISSUE TITLE
Web3 ID: Expose prover and verifier functionality

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-base#366]
**Task description**

Like the prover and verifier interface for ID 2.0, we need to define interface types and a prover and verifier.

The types and prover/verifier should be defined in concordium-base, and defined in such a way that they can be used from Wasm. In particular this means that concurrency should be limited for the wasm platform since that is not supported.

**Sub-tasks**
- [ ] Define DID type to refer to new types of credentials.
- [ ] Define interface types for input statements and proofs.
- [ ] Define prover and verifier interface.
