### ISSUE TITLE
Move relevant blocksummary types from concordium-node to concordium-base

### ISSUE THREAD

**Issue by abhconcordium** [Concordium/concordium-base#46]
**Task description**
Due to historical reasons, there are types  relating to the block summary defined in concordium-node which would make more sense in concordium-base.

Move the query result types to concordium-base, and move all necessary type definitions for this from node to base.

**Sub-tasks**
- [x] Identify which types should be moved
- [x] Add relevant files and definitions to base, on branch  `bstypes-to-base` in concordium-base
- [x] clean up files moved to base
- [x] delete definitions from node and refer to base instead
- [ ] delete definitions from client and refer to base instead
