### ISSUE TITLE
Use ArkWorks BLS12-381 implementation

### ISSUE THREAD

**Issue by annenkov** [Concordium/concordium-base#497]
**Task description**

Change the BLS12-381 curve implementation to https://crates.io/crates/ark-bls12-381
Currently, we use the BLS12-381 curve implementation from an outdated version of the [pairing crate](https://crates.io/crates/pairing/0.15.1). Updating this implementation is not possible because the target group type is not accessible externally and we need it to define custom serialization (see the details [here](https://github.com/zkcrypto/bls12_381/issues/96)).
ArkWorks ecosystem offers many curve implementations and is well-maintained.

However, in order to use an up-to-date version of ArkWorks' BSL12-381, we need to update `ed25519-dalek`, since the versions of `rand` crate must agree. It's also desirable to do so due to the [security advisory related to the version of the crate before 2.0](https://github.com/advisories/GHSA-w5vr-6qhr-36cc).

Both changes (ArkWorks BLS and ed25519-dalek upgrade) should happen at the same time.

**Sub-tasks**
- [x] Define adapters to ArkWorks algebra traits
- [x] Integrate the BLS21-381 curve implementation
- [x] Upgrade `ed25519-dalek` to version 2.
