### ISSUE TITLE
Computing commitment to share would benefit from multiexponentiation

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-base#60]
**Task description**

The function `id::utils::commitment_to_share` would benefit from multiexponentiation.
This would increase performance in a function that is used a fair amount.

**Sub-tasks**
- [x] Benchmark identity and credential creation before the change
- [x] Write the above mentioned function using multiexp.
- [x] Benchmark identity and credential creation after the change
